### ISSUE TITLE
Stitching parameters for persistent duplications

### ISSUE THREAD

**Issue by freblisna** [ChristophKirst/ClearMap2#106]
I'm trying to stitch tiles composed of dense but distinct nuclei in sagittal brain planes but I keep finding duplications or misalignments. I've tried a bunch of different settings including increasing the search radius but I can't eliminate the problem. There are many planes where stitching appears to work perfectly and many where it doesn't. What parameters can I play with that might improve this? Much more frequently, I see duplication along the Y axis, rather than along the X axis, and I've tried measuring the # of pixels misaligned and increasing the Y search radius beyond that number. I'm using a 4x4 grid of z-stack images from the ultramicroscope II (2160x2560 pixels per tile). I imaged with 15% overlap in X and Y directions, z-step = 45 micrometers (thick steps, not 4.5 um). x-shift = +/- 45, y-shift = +/- 60, z-shift = +/- 23. X depth = 500, Y depth = 443. For background: threshold = 500 and number of pixels = 100. I recently started clipping aggressively at 8000 instead of 25000 to focus only on the nuclei, which are around 1000 to 6500 in 16-bit intensity. I would have expected the far step size to pose a problem for stitching since I would not expect to see the same nuclei between pictures, but since I used a sheet NA of 0.105, the sheet thickness is fairly high at the edges and so I can see the same nuclei consistently between 2 steps.

![image](https://user-images.githubusercontent.com/62805456/155568593-7a8163ca-c7da-4939-b2ea-81eedf85d7ee.png)

**Comment by andrewsilberfeld** [comment]
Much more frequently, I've seen persistent duplications along the Y axis with relatively few duplications along the X axis.
