### ISSUE TITLE
Question about the unit of vasculature radius

### ISSUE THREAD

**Issue by mahsa106** [ChristophKirst/ClearMap2#119]
After binarization and atlas registration, what are the units for the final data? 

For example, are the measured radius in pixels or µm? Is it the same for the coordinates?

**Comment by nicolasrenier** [comment]
Hi Mahsa, the units are pixels for the radius, given either in the raw resolution, or in the atlas resolution. It is given at sub-pixel resolution for both, as this is an average over the whole edge. Coordinates are also in pixels, and you also have both raw coordinates (usually between 0 and up to 8000), and atlas coordinates (usually between 0 and 500, but with subpixel resolution).
