### ISSUE TITLE
import ClearMap.Compile fails

### ISSUE THREAD

**Issue by cardinger** [ChristophKirst/ClearMap2#121]
Hello,

I am unable to compile the ClearMap modules. I am attempting to run this on Ubuntu 22.04. I did modify the ClearMap_stable.yml file from pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1 to pytorch-cpu=1.0.0=py3.6_cpu_1, but I believe this should work. Thanks in advance. 

![image](https://github.com/ChristophKirst/ClearMap2/assets/68652535/904a4e0a-7b09-464e-8f17-3bacf897bf50)
![image](https://github.com/ChristophKirst/ClearMap2/assets/68652535/c85d7bb6-bed0-4111-9f35-970a22a1e35d)

**Comment by enochleestanford** [comment]
How did you fix it?
