### ISSUE TITLE
Pytorch version not available anymore

### ISSUE THREAD

**Issue by cardinger** [ChristophKirst/ClearMap2#122]
pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1, which is called in the .yml file is not available anymore. 
```

(base) foo@bar:~/sw/ClearMap/ClearMap2$ conda env create -f ClearMap_stable.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - pytorch==1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
```

**Comment by crousseau** [comment]
A new version of clearmap with a graphical interface is coming soon. All packages have been bumped. It is currently available for prevew on the "dev" branch with new yml file, including one where python is updated to 3.9.

**Comment by cardinger** [comment]
Thanks so much for getting back to me. I successfully installed ClearMap2.1 yesterday. I am trying to use it to initially gather cFOS counts in each brain region in the right hemisphere of 64 brains total which represent 3 different treatment groups. Are there any rough edges with this preview version that you could let me know about?

**Comment by enochleestanford** [comment]
> Thanks so much for getting back to me. I successfully installed ClearMap2.1 yesterday. I am trying to use it to initially gather cFOS counts in each brain region in the right hemisphere of 64 brains total which represent 3 different treatment groups. Are there any rough edges with this preview version that you could let me know about?

How did you install ClearMap2.1?

**Comment by enochleestanford** [comment]
> pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1, which is called in the .yml file is not available anymore.
> 
> ```
> 
> (base) foo@bar:~/sw/ClearMap/ClearMap2$ conda env create -f ClearMap_stable.yml
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - pytorch==1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
> ```

I had the same error. Can you help me fix it?

**Comment by cardinger** [comment]
> > Thanks so much for getting back to me. I successfully installed ClearMap2.1 yesterday. I am trying to use it to initially gather cFOS counts in each brain region in the right hemisphere of 64 brains total which represent 3 different treatment groups. Are there any rough edges with this preview version that you could let me know about?
> 
> How did you install ClearMap2.1?

Apologies for the delay. I followed the instructions that they have for installation in the dev branch but used `./install_gui.sh ClearMapUi39.yml` to run the software with Python 3.9. Did you get it figured out?

**Comment by crousseau** [comment]
@cardinger Re the rough edges, the lastest version on dev should be pretty smooth. Hoping to release soon.

**Comment by cardinger** [comment]
> @cardinger Re the rough edges, the lastest version on dev should be pretty smooth. Hoping to release soon.

It works great! Since late May when I opened this issue, I have used it to get cell counts for 64 brains across 3 different treatment groups with no issues. Thanks so much for all of your help troubleshooting and congrats on the upcoming release!
