### ISSUE TITLE
Wobbly Stitcher crashing

### ISSUE THREAD

**Issue by narasa0** [ChristophKirst/ClearMap2#133]
Hi, 

I am trying to use wobblyStitcher to stitch dataset acquired by UMII using the 4x objective. 

During the setup of the scripts, when I set the overlaps to x=45 and y=256, the stitcher crashes. Please let me know as to how to fix the issue. 

Thanks,
Arun

**Comment by crousseau** [comment]
@narasa0 

Hi, it seems a lot for the overlap in y. I have seen instances where a large overlap was creating issues. You could try precroping in that dimension to reduce the overlap. I'll see on our side too.

**Comment by narasa0** [comment]
@crousseau 

I pre-cropped and saved the files using ImageJ. Now, when I run the Wobblystitcher, The io is not reading it as OME-tiff, but as a tiff file, so the

**Comment by narasa0** [comment]
@crousseau 

I used ImageJ to crop the files and then re-save them. But, ImageJ saves it as tiff file and not ome.tiff. So, the tiff file reader is not reading in the meta data properly and I am not able to stitch now. 

Do you have any code that I can use for which I do this pre-cropping on the fly in WobblyStitcher. 

Thanks,
Arun

**Comment by crousseau** [comment]
@narasa0 
Assuming you are using the UI, you could try the code below:
First copy your sample folder and then (after replacing the arguments by meaningful ones in the last line)
```
from ClearMap.IO import IO as clearmap_io
from ClearMap.processors.sample_preparation import init_preprocessor

def batch_crop(folder, crop_x=0, crop_y=0, suffix='_cropped'):
    preproc = init_preprocessor(folder)

    shape = clearmap_io.shape(preproc.workspace.file_list('raw')[-1])
    for f_path in preproc.workspace.file_list('raw'):
        img = clearmap_io.read(f_path)
        cropped_img = img[crop_x:shape[0] - crop_x, crop_y:shape[1] - crop_y, :]
        cropped_path = f_path.replace('.ome.tif', f'{suffix}.ome.tif')
        clearmap_io.write(cropped_path, cropped_img)

batch_crop('/some/clearmap/sample/folder/', crop_x=000, crop_y=000)
```

**Comment by narasa0** [comment]
Thanks for the code.
