### ISSUE TITLE
Visualisation options for CellMap results 

### ISSUE THREAD

**Issue by VeronikaValova** [ChristophKirst/ClearMap2#85]
Is it possible to generate a colour-coded 3D rendering of the mouse brain atlas containing the cells detected in the CellMap pipeline? For example, something similar to the image provided under 'Graph Visualisation' in the TubeMap tutorial? 
I have run the cell-alignment and annotation steps in CellMap using my own dataset, and have exported the results as a .csv file, but am unsure how to visualise the results.

**Comment by crousseau** [comment]
Hi, 
This is now included in the graphical interface.
